config/routes.rb
Animephile::Application.routes.draw do
  root :to => 'comics#index'
  
  resources :comics do
    resources :pages 
  end
end

app/models/comic.rb
require 'rubygems'
require 'nokogiri'
require 'open-uri'
require 'cgi'


class Comic < ActiveRecord::Base
  attr_accessible :title, :url, :total_page 
  has_many :pages 
  
  # Comic.create_and_parse_images('birthday',  'http://www.animephile.com/hentai/birthday.html?ch=Volume+01',  210)
  # Comic.extract_images('My Mother',  'http://www.animephile.com/hentai/my-mother.html?ch=Volume+01',  3)
  def self.extract_images(title, url, total_page)
    images = [] 
    
    begin
      (1..total_page).each do |page_number|
        # http://www.animephile.com/hentai/my-mother.html?ch=Volume+01      &page=191
        page_url = url + "&page=#{page_number}"
        page = Nokogiri::HTML(open(  page_url     ))  
        
        result = page.css("#mainimage")
        images <<  result.map {|x| x['src'] } .first
         
      end
      
      return images
      
    rescue 
      return nil 
    end
    
    
  end
  
  def self.create_and_parse_images(title, url, total_page )
    images = self.extract_images(title, url, total_page )
    
    if not images.nil? and images.length != 0 
      comic = self.create :title => title, :url => url, :total_page => total_page 
      comic.create_pages( images )
    end 


    comic.pages.each {|x| x.save_file }
  end
  
  def create_pages( images ) 
    page_number = 1 
    images.each do |  image_url |
      regex = /(http:.+\.jpg)/i
      regex.match image_url
      cleaned_image_url = $1
      
      result_page = Page.create :comic_id => self.id, :page_number => page_number, 
              :image_url => cleaned_image_url

      # result_page.save_file
              
      page_number += 1
    end
  end
end


=begin
  
  directory_name = "#{Rails.root.to_s}/public/result/1"
  Dir.mkdir(directory_name) unless File.exists?(directory_name)


  File.open( directory_name , "wb") do |saved_file|
  # the following "open" is provided by open-uri

  the_url = "http://www.animephile.com/mangagallery/Chounyuu For You/Volume 01/chounyuu_v01_168.JPG"
  awesome_url = the_url.gsub(" " , "%20") 


    open( awesome_url , "rb") do |read_file|
     saved_file.write(read_file.read)
    end
  end
=end

app/models/page.rb
class Page < ActiveRecord::Base
  attr_accessible :comic_id, :page_number, :image_url, :local_url
  belongs_to :comic

  def save_file

  	comic_id = comic.id.to_s
  	current_id = self.id.to_s
  	puts "/result/#{comic_id}/#{current_id}"  


  	master_location = "#{Rails.root.to_s}/public/result/"

  	directory_name = master_location + comic.id.to_s + "/"

  	file_name = directory_name + self.id.to_s


	 Dir.mkdir(directory_name) unless File.exists?(directory_name)


	  the_url =  self.image_url # "http://www.animephile.com/mangagallery/Chounyuu For You/Volume 01/chounyuu_v01_168.JPG"
	  awesome_url = the_url.gsub(" " , "%20") 

	  system( "wget -O #{file_name}  #{awesome_url}"  )


	  # File.open( file_name , "wb") do |saved_file|
	  # # the following "open" is provided by open-uri

	  # the_url =  self.image_url # "http://www.animephile.com/mangagallery/Chounyuu For You/Volume 01/chounyuu_v01_168.JPG"
	  # awesome_url = the_url.gsub(" " , "%20") 


	  #   open( awesome_url , "rb") do |read_file|
	  #    saved_file.write(read_file.read)
	  #   end
	  # end

	  self.local_url = "/result/#{comic_id}/#{current_id}"  
	  self.save


  end
  
   
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/comics_controller.rb
 
class ComicsController < ApplicationController
  def index
    
    
    
    @comics = Comic.page(params[:page]).per( 5 ).order("id DESC")
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    @comic = Comic.find_by_id params[:comic_id]
    @pages = @comic.pages.order("page_number ASC")
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comics_helper.rb
module ComicsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/comics/index.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron">
    <h1>Yo bro! slow page loading?</h1>
    <p class="lead">This app will help you to scrap those comic pages and display it on one page</p>
  </div>
<% end %>

<% @comics.each do |comic| %>
 <h4><%= link_to comic.title , comic_pages_url( comic ) %></h4>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en"><head>
    <meta charset="utf-8">
    <title>Template · Bootstrap</title>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta name="description" content="">
    <meta name="author" content="">
		<%=	stylesheet_link_tag 'application'%>
		
    <!-- Le styles -->
     <style type="text/css">
      body {
        padding-top: 20px;
        padding-bottom: 40px;
      }

      /* Custom container */
      .container-narrow {
        margin: 0 auto;
        max-width: 700px;
      }
      .container-narrow > hr {
        margin: 30px 0;
      }

      /* Main marketing message and sign up button */
      .jumbotron {
        margin: 60px 0;
        text-align: center;
      }
      .jumbotron h1 {
        font-size: 72px;
        line-height: 1;
      }
      .jumbotron .btn {
        font-size: 21px;
        padding: 14px 24px;
      }

      /* Supporting marketing content */
      .marketing {
        margin: 60px 0;
      }
      .marketing p + h4 {
        margin-top: 28px;
      }
    </style>
 
    
		<noscript>
			<%= stylesheet_link_tag 'nojs' %>
		</noscript>
		
		<link href="//s3.amazonaws.com/wrapbootstrap/live/imgs/favicon.ico" rel="shortcut icon">
  </head>

  <body>

    <div class="container-narrow">

      <div class="masthead">
        <ul class="nav nav-pills pull-right">
          <li class="active">
						<%= link_to "Home", root_url %>
					</li> 
        </ul>
        <h3 class="muted"><%= link_to 'Comic Reader', root_url %></h3>
      </div>

      <hr>

      <%= yield :jumbotron %>

      <hr>

      <div class="row-fluid marketing">
        <div class="span12">
					<%= yield %> 
         
        </div>

      
      </div>

      <hr>

      <div class="footer">
        <p>© Company 2013</p>
      </div>

    </div> <!-- /container -->

    <%#= image_tag Page.last.local_url  %> 

    <%= image_tag( Page.order("id ASC").first.local_url , :alt => "awesome") %>


		<!-- Le HTML5 shim, for IE6-8 support of HTML5 elements -->
    <!--[if lt IE 9]>
      <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
    <![endif]-->	

		<%= javascript_include_tag 'application' %>
   
</body>
</html>


 

app/views/pages/index.html.erb
<% content_for :jumbotron do %>
	<div class="jumbotron">
    <h1><%= @comic.title %></h1>
  </div>
<% end %>



<% @pages.each do |page| %>

	<!--start: blog -->
	<div class="blog clearfix">
		<div class="span12 img-polaroid blog-img" style='text-align:center;'>
					<%= image_tag page.local_url  %> 
    </div>

         
		
 	</div><!--end: blog -->



<% end %>

 